# .kitchen.yml or opentsdb_handler
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[opentsdb]
      - recipe[opentsdb_handler::default]
    attributes:
      opentsdb_handler:
        hostname: localhost
