# .kitchen.yml or opentsdb_handler
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 4242, host: 4242}]
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[opentsdb::install]
      - recipe[opentsdb::start]
      - recipe[opentsdb_handler]
      - recipe[opentsdb_handler::test_helpers]
    attributes:
      opentsdb:
        hbase_version: "0.94.27"
      opentsdb_handler:
        hostname: localhost
        run_status:
          elapsed_time: true
        metrics:
          test_handler_with_tags:
            name: "test.withtags"
            value: 1
            tags:
              test_tag: "test_value"
          test_handler_without_tags:
            name: "test.withouttags"
            value: 1
          test_handler_with_run_status:
            name: "test.withrunstatus"
            value: 1
            run_status_tag: true

